Модуль 7. Задания 3 и 4
js-tasks-ru/jsbasic-20230928_ai69 pull request #17
Opened 2023-11-02 17:50 UTC by artigor69

Здравствуйте. Не получается пройти тесты, хотя все вроде работает, по крайней мере так как я понял из задания.

2023-11-02 17:51 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-11-05 10:08 UTC, koalex requested changes

2023-11-05 10:08 UTC, koalex commented on 7-module/3-task/index.js
> +    this.#slider.addEventListener("mousedown", this.onMouseDown);
`this.#slider.addEventListener("click", this.onMouseDown);`

2023-11-05 10:08 UTC, koalex commented on 7-module/4-task/index.js
> +        document.removeEventListener('pointerup', thisUp);
По заданию ещё нужно генерировать событие 
```
this.elem.dispatchEvent(
       new CustomEvent('slider-change', {
         detail: this.value,
         bubbles: true
       })
);
```

2023-11-05 15:17 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-11-05 15:18 UTC, artigor69 commented on 7-module/4-task/index.js
> +        document.removeEventListener('pointerup', thisUp);
Спасибо.
Гляжу в книгу - вижу фигу, это про меня

2023-11-05 18:17 UTC, koalex approved these changes

2023-11-05 18:17 UTC, merged